# Generated by Django 6.0 on 2026-05-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pin',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
