# Generated by Django 6.0 on 2026-07-27 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='tier',
            field=models.CharField(choices=[('TierOne', 'TierOne'), ('TierTwo', 'TierTwo'), ('TierThree', 'TierThree')], default='TierOne', max_length=20),
        ),
    ]
