# Generated by Django 6.0 on 2026-07-28 23:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_account_address_account_dob_account_nok_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='utility_bill',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='raw'),
        ),
    ]
