# Generated by Django 6.0 on 2026-07-29 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_account_utility_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='tier',
            field=models.CharField(choices=[('TierOne', 'Tier 1'), ('TierTwo', 'Tier 2'), ('TierThree', 'Tier 3')], default='TierOne', max_length=20),
        ),
    ]
