# Generated by Django 6.0 on 2026-07-29 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_account_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='tier',
            field=models.CharField(choices=[('Tier 1', 'Tier 1'), ('Tier 2', 'Tier 2'), ('Tier 3', 'Tier 3')], default='Tier 1', max_length=20),
        ),
    ]
